In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('./input'):
    for filename in filenames:
        continue
        #print(os.path.join(dirname, filename))
import random 
# Any results you write to the current directory are saved as output.

In [3]:
#!pip install -U tensorflow-gpu

In [4]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [5]:
import os
print(os.listdir('./input/coic2/flowers/'))

['daisy', '.ipynb_checkpoints', 'dandelion', 'rose', 'sunflower', 'tulip']


In [6]:
import cv2
from PIL import Image
from tqdm import tqdm

In [7]:
x=[]
y=[]
IMG_SIZE=150
FLOWER_DAISY_DIR='./input/coic2/flowers/daisy'
FLOWER_SUNFLOWER_DIR='./input/coic2/flowers/sunflower'
FLOWER_TULIP_DIR='./input/coic2/flowers/tulip'
FLOWER_DANDI_DIR='./input/coic2/flowers/dandelion'
FLOWER_ROSE_DIR='./input/coic2/flowers/rose'
#flower_class_dir=['./input/coic2/flowers/daisy','./input/coic2/flowers/tulip','./input/coic2/flowers/sunflower',
#                  './input/coic2/flowers/dandelion','./input/coic2/flowers/rose']
def make_train_data(name,DIR,x,y):
    for img in tqdm(os.listdir(DIR)):
        path = os.path.join(DIR,img)
        img = cv2.imread(path,cv2.IMREAD_COLOR)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        x.append(np.array(img))
        y.append(name)

In [8]:
make_train_data('Daisy',FLOWER_DAISY_DIR,x,y)
make_train_data('Sunflower',FLOWER_SUNFLOWER_DIR,x,y)
make_train_data('Tulip',FLOWER_TULIP_DIR,x,y)
make_train_data('Dandelion',FLOWER_DANDI_DIR,x,y)
make_train_data('Rose',FLOWER_ROSE_DIR,x,y)

100%|██████████| 735/735 [00:01<00:00, 478.90it/s]


In [9]:
print(len(x),len(y))

4086 4086


In [10]:
import matplotlib.pyplot as plt
fig,ax=plt.subplots(5,2)
fig.set_size_inches(15,15)
for i in range(5):
    for j in range (2):
        l=random.randint(0,len(y))
        ax[i,j].imshow(x[l])
        ax[i,j].set_title('Flower: '+y[l])
        
plt.tight_layout()

In [11]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
le=LabelEncoder()
Y=le.fit_transform(y)
print(Y)
Y=to_categorical(Y,5)
X=np.array(x)
X=X/255

[0 0 0 ... 2 2 2]


In [12]:
print(Y)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [14]:
print(type(x_train))

<class 'numpy.ndarray'>


In [15]:
print(np.random.seed(42))

None


In [16]:
# # modelling starts using a CNN.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Activation,Dropout
from tensorflow.keras.optimizers import Adam,Adadelta



In [17]:
print(type(generator.fit(x_train)),generator.fit(x_train))

NameError: name 'generator' is not defined

In [ ]:

model.compile(optimizer=Adam(lr=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.build(input_shape=[None, 150,150,3])
model.summary()

In [ ]:
type(x_train)

In [ ]:
batch_size=32
epochs=35
History = model.fit_generator(generator.flow(x_train,y_train, batch_size=batch_size),
                              epochs = epochs, validation_data = (x_test,y_test),
                              verbose = 1, steps_per_epoch=x_train.shape[0] // batch_size)
#History=model.fit(x_train, y_train,validation_data = (x_test,y_test), batch_size=32, epochs=10)

In [ ]:
TEST_DIR='./input/coic2/unlabel-flowers'
x_final_test=[]
"""
def make_test_data(TEST_DIR,x):
    for img in tqdm(os.listdir(TEST_DIR)):
        path = os.path.join(TEST_DIR,img)
        img = cv2.imread(path,cv2.IMREAD_COLOR)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        x.append(np.array(img))
make_test_data(TEST_DIR,x_final_test)
"""
for i in range(1,176):
    path='./input/coic2/{}.png'.format(i)
    pic=cv2.imread(path,cv2.IMREAD_COLOR)
    x_final_test.append(np.array(pic))


In [ ]:
x_final_test=np.array(x_final_test)/255
print(type(x_final_test),x_final_test.shape)

In [ ]:
tmp=model.predict(x_final_test)

In [ ]:
#daisy=1, dandelion=2, rose=3, sunflower=4, tulip=5.


In [ ]:
ans=[]
l=[]
for i,pro in enumerate(tmp):
    l=[i+1,pro.argmax()+1]
    ans.append(l)

In [ ]:
print(ans)

In [ ]:
sub =  pd.DataFrame(ans)
sub = sub.rename(index=str, columns={0: "id", 1: "Class"})
sub.to_csv('submission2.csv', index=False)